### ISSUE TITLE
Filtering does not seem to work

### ISSUE THREAD

**Issue by eddpascoal** [Cloud-Architects/cloudiscovery#153]
Hi,

wonder if I'm using a correct command or not but looking at the report I would like to filter by a specific stackname. I wonder if this is possible.

`cloudiscovery aws-all --region-name xx-xxxxxxx --profile-name my-profile-name --filter="Name=StackName;Value=myStackname"`

I also tried one very similar approach from readme.
`cloudiscovery aws-all --region-name xx-xxxxxxx --profile-name my-profile-name --filter="Name=type;Value=aws_cloudformation_stack"`

**Result**: 
- it seems to export the same HTML without any filtering

**Context**
OS: (using WSL1):
Linux 4.4.0-18362-Microsoft #1049-Microsoft Thu Aug 14 12:01:00 PST 2020 GNU/Linux

my python requirements export is:
`boto3==1.15.14
botocore==1.18.14
cachetools==4.1.1
cloudiscovery==2.2.3
contextvars==2.4
diagrams==0.17.0
diskcache==5.0.3
graphviz==0.13.2
immutables==0.14
ipaddress==1.0.23
Jinja2==2.11.2
jmespath==0.10.0
MarkupSafe==1.1.1
python-dateutil==2.8.1
s3transfer==0.3.3
six==1.15.0
urllib3==1.25.10`

**Comment by eddpascoal** [comment]
I also tried to use tag filtering and does not work besides the comment below:

**tags only for now, you must specify name and values**
```
  -h, --help            show this help message and exit
  -r REGION_NAME, --region-name REGION_NAME
                        Inform REGION NAME to analyze or "all" to check on all
                        regions. If not informed, try to get from config file
  -p PROFILE_NAME, --profile-name PROFILE_NAME
                        Profile to be used
  -l LANGUAGE, --language LANGUAGE
                        Available languages: pt_BR, en_US
  --verbose [VERBOSE], --verbose [VERBOSE]
                        Enable debug mode to sdk calls (default false)
  -f FILTERS, --filters FILTERS
                        filter resources (tags only for now, you must specify
                        name and values); multiple filters are possible to
                        pass with -f <filter_1> -f <filter_2> approach, values
                        can be separated by : sign; example:
                        Name=tags.costCenter;Value=20000:'20001:1'
  -s SERVICES, --services SERVICES
                        Define services that you want to check, use ","
                        (comma) to separate multiple names. If not passed,
                        command will check all services.
```

I also notice that **Filterable** class is empty.

```
class Filterable:
    pass
```

**Comment by meshuga** [comment]
Thanks for rising the issue! We added this command recently and finding out what would be most useful to have.

Filters for aws-all seems to be an important feature 👍

**Comment by patrykorwat** [comment]
There's a bug in filter functionality. Thanks @eddpascoal for raising the issue!
