### ISSUE TITLE
Distorted diagram image

### ISSUE THREAD

**Issue by supernova789** [Cloud-Architects/cloudiscovery#154]
Hi,

I'm trying to generate a aws-vpc report and diagram. Eventhough I'm able to generate the report, the diagram image is not generated properly, with distorted and all the elements of the image created at the center of page overlapping each other.

Please Help !

The command i run:  cloudiscovery aws-vpc --vpc-id vpcID --region-name regionName --diagram yes --verbose

and the error i get is : 

You've found a bug! Please, open an issue in GitHub project
https://github.com/Cloud-Architects/cloudiscovery/issues

Python:        3.6.8 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
boto3 version: 1.15.13
Platform:      Linux-3.10.0-1127.19.1.el7.x86_64-x86_64-with-centos-7.8.2003-Core

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/cloudiscovery/shared/error_handler.py", line 21, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/cloudiscovery/shared/diagram.py", line 299, in generate_diagram
    self.draw_diagram(ordered_resources=ordered_resources, relations=relations)
  File "/usr/local/lib/python3.6/site-packages/diagrams/__init__.py", line 147, in __exit__
    self.render()
  File "/usr/local/lib/python3.6/site-packages/diagrams/__init__.py", line 189, in render
    self.dot.render(format=self.outformat, view=self.show, quiet=True)
  File "/usr/local/lib/python3.6/site-packages/graphviz/files.py", line 209, in render
    quiet=quiet)
  File "/usr/local/lib/python3.6/site-packages/graphviz/backend.py", line 206, in render
    run(cmd, capture_output=True, cwd=cwd, check=True, quiet=quiet)
  File "/usr/local/lib/python3.6/site-packages/graphviz/backend.py", line 172, in run
    output=out, stderr=err)
graphviz.backend.CalledProcessError: Command '['sfdp', '-Tpng', '-O', '301908261546_us-east-1_vpc-3456496b_vpc']' returned non-zero exit status 1. [stderr: b"Warning: node '745279fb65f44d0c9c5818604ecd5833', graph 'AWS VPC vpc-3456496b Resources - Region us-east-1' size too small for label\nError: remove_overlap: Graphviz not built with triangulation library\n"]

All Help Appreciated !

**Comment by sdaam007** [comment]
Ok

**Comment by patrykorwat** [comment]
I hope steps provided in https://stackoverflow.com/questions/34228395/ubuntu-graphviz-sfdp-not-working will help you. We use sfdp engine to render VPC diagrams and some of the distribution packages are not shipped with this engine.

On a side note, I started work on #97 and introduction of diagrams.net compatible diagrams. It'll allow better interoperability and enable you to work on the generated diagrams.

**Comment by patrykorwat** [comment]
The VPC diagram migrated to diagrams.net. The issue can be closed as is linked to graphviz.
