### ISSUE TITLE
(AWS) Resource filtering by tags

### ISSUE THREAD

**Issue by meshuga** [Cloud-Architects/cloudiscovery#30]
Tags in AWS are used for various purposes to group resources [1].

It should be possible to filter out detected resources by tags, so that it would be possible to report only a specific group of resources instead of all resources within an account.

There can be an additional parameter for that purpose that would accept tag name and value(s) `--filter="Name=tags.costCenter;Value=20000:'20001:1'"`. The mentioned example reports resources only with tag `tags.costCenter` with values `20000` and `20001:1`.

[1] https://d1.awsstatic.com/whitepapers/aws-tagging-best-practices.pdf

**Comment by leandrodamascena** [comment]
Closed #81 #80
