### ISSUE TITLE
(AWS) Error running check SYNTHETICSCANARIES.get_resources

### ISSUE THREAD

**Issue by JoshiiSinfield** [Cloud-Architects/cloudiscovery#69]
Hi,

I get the following error when it's scanning.
Command I ran: 
`clouddiscovery aws-vpc --region-name eu-west-1 --profile-name XXXX`
Running: 
python --version                                                                                                                            
Python 3.7.5
pip --version
pip 20.0.2 from /usr/local/lib/python3.7/site-packages/pip (python 3.7)
pip show clouddiscovery
Name: clouddiscovery
Version: 2.0.508
Summary: The tool to help you discover resources in the cloud environment
Home-page: https://github.com/Cloud-Architects/cloud-discovery
Author: Cloud Architects
Author-email: None
License: Apache License 2.0
Location: /usr/local/lib/python3.7/site-packages
Requires: diagrams, boto3, ipaddress
Required-by:
aws --version
aws-cli/2.0.18 Python/3.8.3 Darwin/19.3.0 botocore/2.0.0dev22

Collecting data from SQS Queue Policy...
Collecting data from Subnets...

Error running check SYNTHETICSCANARIES.get_resources. Error message Unknown service: 'synthetics'. Valid service names are: accessanalyzer, acm, acm-pca, alexaforbusiness, amplify, apigateway, apigatewaymanagementapi, apigatewayv2, appconfig, application-autoscaling, application-insights, appmesh, appstream, appsync, athena, autoscaling, autoscaling-plans, backup, batch, budgets, ce, chime, cloud9, clouddirectory, cloudformation, cloudfront, cloudhsm, cloudhsmv2, cloudsearch, cloudsearchdomain, cloudtrail, cloudwatch, codebuild, codecommit, codedeploy, codeguru-reviewer, codeguruprofiler, codepipeline, codestar, codestar-connections, codestar-notifications, cognito-identity, cognito-idp, cognito-sync, comprehend, comprehendmedical, compute-optimizer, config, connect, connectparticipant, cur, dataexchange, datapipeline, datasync, dax, detective, devicefarm, directconnect, discovery, dlm, dms, docdb, ds, dynamodb, dynamodbstreams, ebs, ec2, ec2-instance-connect, ecr, ecs, efs, eks, elastic-inference, elasticache, elasticbeanstalk, elastictranscoder, elb, elbv2, emr, es, events, firehose, fms, forecast, forecastquery, frauddetector, fsx, gamelift, glacier, globalaccelerator, glue, greengrass, groundstation, guardduty, health, iam, imagebuilder, importexport, inspector, iot, iot-data, iot-jobs-data, iot1click-devices, iot1click-projects, iotanalytics, iotevents, iotevents-data, iotsecuretunneling, iotthingsgraph, kafka, kendra, kinesis, kinesis-video-archived-media, kinesis-video-media, kinesis-video-signaling, kinesisanalytics, kinesisanalyticsv2, kinesisvideo, kms, lakeformation, lambda, lex-models, lex-runtime, license-manager, lightsail, logs, machinelearning, macie, managedblockchain, marketplace-catalog, marketplace-entitlement, marketplacecommerceanalytics, mediaconnect, mediaconvert, medialive, mediapackage, mediapackage-vod, mediastore, mediastore-data, mediatailor, meteringmarketplace, mgh, migrationhub-config, mobile, mq, mturk, neptune, networkmanager, opsworks, opsworkscm, organizations, outposts, personalize, personalize-events, personalize-runtime, pi, pinpoint, pinpoint-email, pinpoint-sms-voice, polly, pricing, qldb, qldb-session, quicksight, ram, rds, rds-data, redshift, rekognition, resource-groups, resourcegroupstaggingapi, robomaker, route53, route53domains, route53resolver, s3, s3control, sagemaker, sagemaker-a2i-runtime, sagemaker-runtime, savingsplans, schemas, sdb, secretsmanager, securityhub, serverlessrepo, service-quotas, servicecatalog, servicediscovery, ses, sesv2, shield, signer, sms, sms-voice, snowball, sns, sqs, ssm, sso, sso-oidc, stepfunctions, storagegateway, sts, support, swf, textract, transcribe, transfer, translate, waf, waf-regional, wafv2, workdocs, worklink, workmail, workmailmessageflow, workspaces, xray
Collecting data from VPC Endpoints...
Collecting data from VPC Peering...

**Comment by leandrodamascena** [comment]
Hi!

The only service with problem is SYNTHETICSCANARIES.get_resources? 

Just to check... Did you configured policies to allow "synthetics:DescribeCanaries" permission?

Thank you for you report :)

**Comment by leandrodamascena** [comment]
@JoshiiSinfield I can't reproduce this error.. I thinks this error is a pip package problem.. 

Try this:

```
git clone https://github.com/Cloud-Architects/cloudiscovery.git .

MacOS or Linux
python3 -m venv env
source venv/bin/activate

Windows:
python -v venv venv
.\venv\Scripts\activate

pip install -U -r requirements.txt

python clouddiscovery\__init__.py aws-vpc --region-name eu-west-1 --profile-name XXXX
```

We will update pip package this weekend.

**Comment by patrykorwat** [comment]
The error is caused by old botocore. It's recommended to install the package with `-U` option, that is `pip install -U cloudiscovery`.

Ref https://github.com/Cloud-Architects/cloudiscovery#aws-resources
