### ISSUE TITLE
(AWS VPC) More network resources

### ISSUE THREAD

**Issue by meshuga** [Cloud-Architects/cloudiscovery#7]
It would be good to have:
- [x] ALB resources
- [x] Internet Gateway
- [x] NAT Gateway
- [x] VPC/Service Endpoint
- [x] Route tables
- [x] Subnets
- [x] Peered connections
- [x] Security Groups
- [x] NACLs
- [ ] Virtual Private Gateways
- [ ] VPN Connections
- [ ] Client VPN Endpoints

**Comment by leandrodamascena** [comment]
I'm thinking about how to refactor code of print messages... I don't like the way of things are displayed on screen and with lot of new services this will be a big mess..

I'll insert these new services, but will keep on target how to re-design this...

**Comment by leandrodamascena** [comment]
> It would be good to have:
> 
> * [x]  ALB resources

Added ALB and CLASSIC LB check. There are 2 different classes to check cause boto3 implementation works this way..

**Comment by leandrodamascena** [comment]
> It would be good to have:
> 
> * [x]  VPC/Service Endpoint

VPC Service Endpoint is attached to a Network Load Balancer and there is no a simple way to get the information about NLB.. The response of boto3 method describe_vpc_endpoint_services() doesn't have subnet or vpc-id, just have AZ and I can't use this, it's not safe.

But it's not a problem.. When scripts checks NLB, will detect if is using VPC informed or not..
