### ISSUE TITLE
(GENERAL) Update diagrams version to support new icons

### ISSUE THREAD

**Issue by leandrodamascena** [Cloud-Architects/cloudiscovery#76]
Change diagram version to support new IoT and Sagemaker icons.

**Comment by patrykorwat** [comment]
Not to forget, a lot of IAM principals now have own icons

**Comment by leandrodamascena** [comment]
Ok.

**Comment by leandrodamascena** [comment]
I'm closing this issue and reopen when diagram launch new icons.
