### ISSUE TITLE
(AWS) Alert the services that are not available in some region

### ISSUE THREAD

**Issue by leandrodamascena** [Cloud-Architects/cloudiscovery#98]
It would be good to alert the services that is not available and skip check..

![image](https://user-images.githubusercontent.com/4295173/85229740-85164a00-b3e3-11ea-833b-6494fdb26fbc.png)

**Comment by patrykorwat** [comment]
Apart from that, commands execution should be parallelized.

**Comment by leandrodamascena** [comment]
![image](https://user-images.githubusercontent.com/4295173/85379763-0bda3c80-b534-11ea-88dc-40ea21a21ce1.png)

**Comment by leandrodamascena** [comment]
> Apart from that, commands execution should be parallelized.

Agree! Opened issue #104

**Comment by leandrodamascena** [comment]
Closed #105
